// <auto-generated />
using ManageAccountApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ManageAccountApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306092337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManageAccountApp.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("ACCOUNTS", (string)null);
                });

            modelBuilder.Entity("ManageAccountApp.Models.CheckingAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<decimal>("Balance")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("BALANCE");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("INTEREST_RATE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("CHECKING_ACCOUNTS", (string)null);
                });

            modelBuilder.Entity("ManageAccountApp.Models.SavingsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACCOUNT_ID");

                    b.Property<decimal>("Balance")
                        .HasColumnType("NUMBER(18,2)")
                        .HasColumnName("BALANCE");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("INTEREST_RATE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("SAVINGS_ACCOUNTS", (string)null);
                });

            modelBuilder.Entity("ManageAccountApp.Models.CheckingAccount", b =>
                {
                    b.HasOne("ManageAccountApp.Models.Account", null)
                        .WithOne("CheckingAccount")
                        .HasForeignKey("ManageAccountApp.Models.CheckingAccount", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManageAccountApp.Models.SavingsAccount", b =>
                {
                    b.HasOne("ManageAccountApp.Models.Account", null)
                        .WithOne("SavingsAccount")
                        .HasForeignKey("ManageAccountApp.Models.SavingsAccount", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManageAccountApp.Models.Account", b =>
                {
                    b.Navigation("CheckingAccount")
                        .IsRequired();

                    b.Navigation("SavingsAccount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
